name: preparing
description: preparing for building

outputs: 
  deps_folder:
    description: 'Dependencies folder'
    value: ${{ steps.save_deps_folder.outputs.deps_folder }}
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        libx11-dev \
        libxrandr-dev \
        libxcursor-dev \
        libxi-dev \
        libgl1-mesa-dev \
        libglu1-mesa-dev \
        libudev-dev \
        xorg-dev
    - id: save_deps_folder
      shell: bash
      run: echo "::set-output name=deps_folder::$GITHUB_WORKSPACE/deps"
    #- name: Cache dependencies
    #  uses: actions/cache@v4
    #  with:
    #    path: deps
    #    key: ${{runner.os}}-deps