name: preparing
description: preparing for building

outputs: 
  deps_folder:
    description: 'Dependencies folder'
    value: ${{ steps.save_deps_folder.outputs.deps_folder }}

runs:
  using: 'composite'
  steps:
    - name: Cache Linux dependencies
      if: runner.os == 'Linux'
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-
    - name: Install dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' | sudo tee /etc/apt/apt.conf.d/01keep-debs
        sudo apt-get update -o Dir::Etc::sourcelist="sources.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
        sudo apt-get install -y --no-install-recommends \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libudev-dev
    - id: save_deps_folder
      if: runner.os == 'Linux'
      shell: bash
      run: echo "deps_folder=$GITHUB_WORKSPACE/deps" >> $GITHUB_OUTPUT
      