project(SFMLExample LANGUAGES CXX)
add_executable(SFMLExample main.cpp)
target_link_libraries(SFMLExample PRIVATE ASCIIlib SFML::Graphics)
target_include_directories(SFMLExample PUBLIC ${INCLUDE_DIR} ${CMAKE_BINARY_DIR}/examples)
if(${SFML_FOUND})
    target_compile_definitions(SFMLExample PRIVATE SFML_FOUND)
endif()