name: CI
on:
    workflow_dispatch:
    push:
      branches: [ master,develop ]
    pull_request:
      branches: [ master,develop ]
jobs:
  BuildWorkflow:
    uses: ./.github/actions/Library/build/Build.yml
  TestWorkflow:
    uses: ./.github/actions/Library/test/Test.yml