name: CI
on:
  push:
    branches: 
      - "*"
env:
  branches:
    develop
    feature
    release
defaults:
  run:
    shell: bash
    

jobs:
  if: ${{ GITHUB_REF##*/ == github.event.repository.default_branch}}
  deploy:
    steps:
      - name: Deploy a library
        run: |
          echo "Prod"
