name: CI
on:
    workflow_dispatch:
    push:
      branches: [ master,develop ]
    pull_request:
      branches: [ master,develop ]
jobs:
  BuildWorkflow:
    uses: ./.github/workflows/Library/Build.yml
  TestWorkflow:
    uses: ./.github/workflows/Library/Test.yml