name: Library.yml
on:
  workflow_call: 
jobs:
  preparing:
    name: preparing
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    outputs:
      deps_folder: ${{ steps.prepare.outputs.deps_folder }}
    steps:
      - uses: actions/checkout@v4
      - id: prepare
        uses: ./.github/actions/Library/preparing
  
  build:
    name: Build Library
    needs: [ preparing ]
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - if: runner.os == 'Linux'
        run: |
          echo "Dependencies folder:" &&
          echo "${{needs.preparing.outputs.deps_folder}}"
      - uses: actions/checkout@v4
      - name: Building Library
        uses: ./.github/actions/Library/build
        with:
          build_type: Debug