name: test.yml
on:
  workflow_call:
jobs:
  unit-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Run unit tests
      run: |
        echo "Run unit tests"
  integration-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Run integration tests
      run: |
        echo "Run integration tests"